version: '3.1'

volumes :
  pfa_jenkins_home: 
    external : true
  sonarqube_data :
  sonarqube_logs :
  sonarqube_extensions :

services:
  sonarqube: 
    image : sonarqube
    volumes :
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - 9000:9000
    
  jenkins:
    image : jenkins/jenkins:lts-jdk17
    volumes:
      - pfa_jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    
